cache:
  directories:
  - $PIP_CACHE_DIR
  - $POETRY_CACHE_DIR
  - $HOME/nix.store

language: nix

env:
  global:
  - PIP_CACHE_DIR=$HOME/.cache/pip
  - POETRY_CACHE_DIR=$HOME/.cache/pypoetry/cache
  jobs:
  - PYTHON_VERSION="35"
  - PYTHON_VERSION="36"
  - PYTHON_VERSION="37"
  - PYTHON_VERSION="38"
  - PYTHON_VERSION="38" PYTEST_ADDOPTS=--elm-version=0.19.0

before_install:
- sudo mkdir -p /etc/nix
- echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
- git lfs version
- git lfs pull
- find . -iname '*.tar.gz'

script:
- nix-shell --argstr pythonVersion "${PYTHON_VERSION}" --run "./ci.sh"

before_cache:
- mkdir -p "$HOME/nix.store"
- nix copy --to "file://$HOME/nix.store" -f shell.nix buildInputs
- ls "$HOME/nix.store"

after_success:
- nix-shell --argstr pythonVersion "${PYTHON_VERSION}" --run "tox -e coverage-report"
- bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
